# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: #YesWeCode Fund
email: info@yeswecodefund.com
description: > # this means to ignore newlines until "baseurl:"
  The #YesWeCode Fund is a partnership of organizations committed to increasing access to technology education for all. The scholarship fund is designed to remove financial barriers for people who are underrepresented in the technology industry, including women and people of color. Students with financial need are encouraged to apply to receive a full-tuition scholarship to attend a full-time, immersive code school and take the first step toward a fulfilling career in technology.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
date_format: "%b %-d, %Y"

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-haml

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  style: compressed
